services:
  gundrabot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gundrabot

    volumes:
      - ..:/usr/src/app:cached
      - gundrabot_node_modules:/usr/src/app/node_modules

    environment:
      NODE_ENV: development

    # If you want to keep the container open:
    command: sleep infinity

volumes:
  gundrabot_node_modules:
